services:
  gitops:
    container_name: gitops
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3333:3333
    networks:
      - main

networks:
  main: