apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images: 
  - name: my-needs-replace-server
    newName: gabrielogregorio/gitops
    newTag: cd-auto-update-this-tag